### ISSUE TITLE
Real world example

### ISSUE THREAD

**Issue by fireridlle** [lequant40/portfolio_allocation_js#10]
Hi. I am just wondering is there any real-world example? Don't really get how to use this package

**Comment by lequant40** [comment]
Hi there!

Actually, my focus shifted from developping this library (initially made to be usable with Google Sheets) to providing similar functionalities through a Web API, much more simple to use -> [https://portfoliooptimizer.io/](https://portfoliooptimizer.io/)

On the Portfolio Optimizer website above, you will find examples of usage, like:
- Optimizing a crypto portfolio (+ sending the associated orders to Binance)
- Replicating an ETF managed by J.P. Morgan
- Analysis where a portfolio is locatedcomapred to the mean-variance efficient frontier

Happy reading :-) !

Cheers,

Roman
